### ISSUE TITLE
How to add a new machine?

### ISSUE THREAD

**Issue by oktay454** [kalaksi/lightkeeper#1]
How to add a new machine?

**Comment by kalaksi** [comment]
You will have to modify `hosts.yml` file in the applications configuration directory.
The location of the directory depends on if you're running a flatpak or not. README should help you find them: https://github.com/kalaksi/lightkeeper#file-locations .

I just added more comments to the `hosts.example.yml`, `templates.example.yml` and `config.example.yml` so check those out too. I also noticed that test-directory was missing configurations so I added those too.

Let me know if you need more help. I'm glad that someone already wants to try this out and it will help me prioritize the work that's relevant to users.

**Comment by kalaksi** [comment]
@oktay454 did you get it to work?

**Comment by oktay454** [comment]
First of all, I apologize for answering late. @kalaksi 

It seems to take some time to understand the logic of YML files.
When adding each server, it is necessary to point out the details.
Will there be a graphical interface work to add machines?

**Comment by kalaksi** [comment]
No problem! The develop-branch with the example configurations (and test-directory too) have some more comments that I recently added. Unfortunately, there's not yet better documentation, but there will be. If you have any specific questions, I can answer you.

And yes, the next feature I will be implementing is graphical interface for adding hosts and I have already decided how to UI will look.

**Comment by oktay454** [comment]
> No problem! The develop-branch with the example configurations (and test-directory too) have some more comments that I recently added. Unfortunately, there's not yet better documentation, but there will be. If you have any specific questions, I can answer you.
Ok. If there is a thing that is attached to my head, I will request your support again. Thanks


> And yes, the next feature I will be implementing is graphical interface for adding hosts and I have already decided how the UI will look.

It is really nice to hear this.
I wish you the success of your work.

**Comment by kalaksi** [comment]
I just published a new version: https://github.com/kalaksi/lightkeeper/releases

Flathub web page doesn't display it yet. It also says version is 0.3.1 but that's because of a mistake I made. I'll have to try to improve the release process so there'd be less chance for mistakes.

Anyway, try it out and ask away if you can't figure something out.

**Comment by kalaksi** [comment]
FYI, 0.4.2 is out now

**Comment by oktay454** [comment]
It's really awesome. Thanks =)

**Comment by oktay454** [comment]
Where do I specify the SSH port of the machines I access from a different SSH port?
Should it be IP:Port?

**Comment by kalaksi** [comment]
No, just the IP or domain name. The SSH settings are currently configured like any other module. Check out the "default"-group configuration. You'll find SSH settings there.

I've been thinking how to make it more visible or clear how the configuration should be done. The reason for using mainly group configurations is that if you have a lot of hosts, you don't want to configure anything to each of them separately but rather as groups.

**Comment by kalaksi** [comment]
Have you managed to add a new machine?

Btw, version 0.5.0 is now out with all kinds of fixes and improvements so I recommend updating.

**Comment by oktay454** [comment]
I added it but I'm having issue #4. I also added a remote machine but it didn't work.

**Comment by kalaksi** [comment]
@oktay454 would you consider this issue resolved?

**Comment by oktay454** [comment]
> @oktay454 would you consider this issue resolved?

@kalaksi Yes, the machine adding feature is quite good
