### ISSUE TITLE
Visual distortion in the menu

### ISSUE THREAD

**Issue by oktay454** [kalaksi/lightkeeper#2]
It doesn't fit in the frame.
![image](https://github.com/kalaksi/lightkeeper/assets/1449620/9b607f62-c75d-4a47-b085-bb84f781085f)
![image](https://github.com/kalaksi/lightkeeper/assets/1449620/2f507758-11fe-4a11-a9aa-12794c0027ce)

**Comment by kalaksi** [comment]
OK, that's odd. It should display scrollbars and it does on my system. Are you using flatpak or building from source?

**Comment by oktay454** [comment]
I use from Flatpak

**Comment by kalaksi** [comment]
I have an idea what the problem might be. I'll soon do a new release with various small fixes.

**Comment by kalaksi** [comment]
0.4.4 is now out. Let me know if this fixes the issues you had.

**Comment by oktay454** [comment]
There does not appear to be any problem with version 0.4.4.
